server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#--- 高可用配置
#spring:
#  profiles: eureka1
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: eureka
#  client:
#    serviceUrl:
#      defaultZone: http://eureka2:8002/eureka/
#
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    serviceUrl:
#      defaultZone: http://eureka1:8001/eureka/